Add error handling for running vg with an invalid repository

diff --git a/bin/vg b/bin/vg
--- a/bin/vg
+++ b/bin/vg
@@ -12,4 +12,10 @@ if [ ! -f "$PATH_TO_NODE" ]; then
   exit 1
 fi
 
+# Attempt to get the path to the .git dir. If it fails, output the error, otherwise continue.
+if ! error_output=$(git rev-parse --absolute-git-dir 2>&1 > /dev/null); then
+  echo "$error_output"
+  exit 1
+fi
+
 nohup "$PATH_TO_NODE" "$PATH_TO_INDEX_JS" "$@" > /dev/null 2>&1 &
